### ISSUE TITLE
Fehler beim Laden der config-Werte in WeatherDataProvider2.py

### ISSUE THREAD

**Issue by RienSte** [wiggal/GEN24_Ladesteuerung#103]
Hallo @wiggal 

beim Aufruf der WeatherDataProvider2.py bekomme ich folgende Fehlermeldung:
![image](https://github.com/user-attachments/assets/b4029c5f-182e-4de7-95b7-cd6344164e24)

Hab dann in den Code geschaut und festgestellt, dass zu Beginn zwar die **FUNCTIONS.functions** importiert werden, allerdings die Variable **config**, die du in Zeile 9 an die Funktion **loadLatestWeatherData** übergibst nicht definiert wird (kein Wert zugewiesen).

Du rufst die beiden Funktionen
```
    basics = FUNCTIONS.functions.basics()
    config = basics.loadConfig(['default', 'weather'])
```
zu Beginn nicht auf. Wenn man das einfügt, läuft das File durch...

(allerdings bekam ich dann von Forecast.Solar die Meldung, dass ich zu schnell erneut abgefragt habe, also komplett bestätigen kann ich es nicht)

SG Stephan

**Comment by wiggal** [comment]
Hi Stephan,
die Funktionen werden in Zeile 62 und 63 aufgefufen, bzw definiert, und dann wird erst die Funktion an Zeile 9 aufgerufen, müsste so weit schon passen.

Ich hab bei der Umstellung auf die Funktionen das Lesen der Varablen in der WeatherDataProvider2.py vergessen.
Werd ich fixen.

Danke für die Meldung

**Comment by wiggal** [comment]
Ja genau,
beim Aufruf wird nur der Teil ab` if __name__ == '__main__':` ausgeführt, `def loadLatestWeatherData(config):` definiert nur eine Funktion, die dann aus dem Hauptprogramm ausgeführt wird ( Zeile 88) .

Wenn ich die Aufrufe (basics und config) in die Zeile 8 kopiere, gehts bei mir auch nicht, ist aber egal.

**Comment by RienSte** [comment]
Ok verstanden. Wieder was gelernt 👍 

Wie gesagt, ich bekam bei dem Test auch einen Fehler von der api... wahrscheinlich dann nur von einer anderen Stelle im Code, so dass es für mich so ausgesehen hat, als wäre das die Lösung. So wie du es beschreibst kann mein Vorschlag ja auch gar nicht gehen.

Mein (erster) Workaround ist (war) dass ich lat, lon, etc einfach in der Funktion fix reingeschrieben habe. Das ging dann definitiv.

**Comment by wiggal** [comment]
Ok,
ich hab mal eine neue WeatherDataProvider2.py gepushed, kannst ja mal testen.

**Comment by RienSte** [comment]
Bekomme die Meldung

> forecast.solar: Die Minuten aus "dataAgeMaxInMinutes" 100 Minuten sind noch nicht abgelaufen!!
> [Now: 2024-09-27 09:14:16.499404] [Data created: 2024-09-27 09:14:00] -> age in min: 0.27499006666666664

Obwohl ich heute noch nix von forecast.solar abgerufen habe.
Ist übrigens die gleiche Meldung wie gestern nach meinem Versuch den Bug zu fixen.

**Comment by wiggal** [comment]
Das bedeutet, dass die weather.json um 09:14:00 erzeugt wurde, egal von welchem Skript.
Dadurch sind die 100 Minuten "Schutzzeit" noch nicht abgelaufen, und es wird nichts abgerufen.

Einfach in der weather.json das Datum "messageCreated": "2024-09-27..." z.B. auf 2023 setzen (mach ich immer).

**Comment by wiggal** [comment]
> Habe die dataAgeMaxInMinutes mal auf 0 gesetzt, dann gehts. Also das py File scheint i.O. zu sein.

So gehts natürlich auch ;-)

**Comment by RienSte** [comment]
Alles klar, ja solarprognose.de hat um 09:14 was geschrieben.
Aber gut, dann schauts soweit i.O. aus 👍

**Comment by wiggal** [comment]
gut, dann ists erledigt
