### ISSUE TITLE
Fehlermeldung in dynamicPrice2

### ISSUE THREAD

**Issue by Manniene** [wiggal/GEN24_Ladesteuerung#121]
Programm lief komplette Woche durch. Seit gestern folgende Meldungungen im Log:

 charging >>>>>>>>>>
Traceback (most recent call last):
  File "/home/GEN24/DynamicPriceCheck.py", line 173, in <module>
    net_power_ii = row_ii[1] - row_ii[2]
                   ~~~~~~~~~~^~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'
*** BEGINN DynamicPriceCheck:  2024-12-20 17:58:01 ***


 charging >>>>>>>>>>
Traceback (most recent call last):
  File "/home/GEN24/DynamicPriceCheck.py", line 155, in <module>
    net_power = row[1] - row[2]
                ~~~~~~~^~~~~~~~
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'
*** BEGINN DynamicPriceCheck:  2024-12-20 21:58:01 ***>>>>> charging >>>>>>>>>>
Traceback (most recent call last):
  File "/home/GEN24/DynamicPriceCheck.py", line 173, in <module>
    net_power_ii = row_ii[1] - row_ii[2]
                   ~~~~~~~~~~^~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'
*** BEGINN DynamicPriceCheck:  2024-12-20 17:58:01 ***


 charging >>>>>>>>>>
Traceback (most recent call last):
  File "/home/GEN24/DynamicPriceCheck.py", line 155, in <module>
    net_power = row[1] - row[2]
                ~~~~~~~^~~~~~~~
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'
*** BEGINN DynamicPriceCheck:  2024-12-20 21:58:01 ***
[DynTrace.log](https://github.com/user-attachments/files/18218038/DynTrace.log)

**Comment by Manniene** [comment]
in dynprice_priv.ini habe ich:
LastprofilNeuTage = 7
Daysback = 7

in der Prog_Steuerung.sqlite steht für 15:00 
 ![image](https://github.com/user-attachments/assets/9c817ae1-8eb1-4bcf-a2de-ea2ba1b6c0de)

Berechtigung für Prog_Steuerung.sqlite ist gegeben. 
Vorschlag: ich erstelle ein neues Lastprofil und prüfe erstmal , ob das Problem wieder auftritt. Musste die Dateiendung von .sqlite auf .txt ändern, damit ich die Datei hochladen konnte.
[Prog_Steuerung.txt](https://github.com/user-attachments/files/18218152/Prog_Steuerung.txt)

**Comment by wiggal** [comment]
Das hier ist der Fehler im Lastprofil:
![grafik](https://github.com/user-attachments/assets/c8494c29-85b3-4976-a671-3f66ab550485)

6-15 steht für 6 = Samstag (da Sonntag = 0), 15 = 15:00 Uhr, Spallte 6 `NULL` dürfte nicht sein, hier sollte der Verbrauch stehen.

Die Fehler sind im neuen Lastprofil auch wieder drinnen, halt an anderen Tagen????
![grafik](https://github.com/user-attachments/assets/966ed917-4b84-418f-ac98-5d2765934dd4)


Wie der Fehler entsteht, muss ich noch suchen.

**Comment by wiggal** [comment]
Um den Fehler zu finden, bräuchte ich auch noch die `PV_Daten.sqlite`. Ich hoffe, sie ist nicht zu groß für einen Upload.

**Comment by Manniene** [comment]
> Um den Fehler zu finden, bräuchte ich auch noch die `PV_Daten.sqlite`. Ich hoffe, sie ist nicht zu groß für einen Upload.

>> [PV_Daten.txt](https://github.com/user-attachments/files/18218343/PV_Daten.txt)

**Comment by Manniene** [comment]
> Das hier ist der Fehler im Lastprofil: ![grafik](https://private-user-images.githubusercontent.com/69506553/397922804-c8494c29-85b3-4976-a671-3f66ab550485.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODA4MzIsIm5iZiI6MTczNDc4MDUzMiwicGF0aCI6Ii82OTUwNjU1My8zOTc5MjI4MDQtYzg0OTRjMjktODViMy00OTc2LWE2NzEtM2Y2NmFiNTUwNDg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDExMjg1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhZjFjN2E0OWZhMzc2YTQ2M2QyYTkyYTg1YTdlMWJjNDgwZmJiMDJmYmMyMzFkODY4NmExYWJhOTE1Y2UwYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JMWofxHzOdZdYaSU4x1TkuAZwXuaLiD_i9HAObhXw_g)
> 
> 6-15 steht für 6 = Samstag (da Sonntag = 0), 15 = 15:00 Uhr, Spallte 6 `NULL` dürfte nicht sein, hier sollte der Verbrauch stehen.
> 
> Die Fehler sind im neuen Lastprofil auch wieder drinnen, halt an anderen Tagen???? ![grafik](https://private-user-images.githubusercontent.com/69506553/397922950-966ed917-4b84-418f-ac98-5d2765934dd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODA4MzIsIm5iZiI6MTczNDc4MDUzMiwicGF0aCI6Ii82OTUwNjU1My8zOTc5MjI5NTAtOTY2ZWQ5MTctNGI4NC00MThmLWFjOTgtNWQyNzY1OTM0ZGQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDExMjg1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExOTFiMDA2ZmI5OGU0Y2NhZGQ0ODU4NThjYzE0MzAzNmY3OGMzZjhmNGYyOGQ2NTg1MDRhZjRjYzk5YmM1NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-V_81jE3_7AaMxKOOEkxDCF-9nY8jO3i-jGAAhiNKoE)
> 
> Wie der Fehler entsteht, muss ich noch suchen.
>> habe noch mal ein Lastprofil erzeugt mit: in dynprice_priv.ini habe ich:
LastprofilNeuTage = 7
Daysback = 20
>> jetzt stehen im Feld Res_Feld2 für alle Tage Werte drin. von 0-00 bis 6-23
>> [Prog_Steuerung.txt](https://github.com/user-attachments/files/18218366/Prog_Steuerung.txt)

**Comment by Manniene** [comment]
Nochmal zur Bestätigung. Sobald Daysback > 7 tritt der Fehler nicht auf

**Comment by wiggal** [comment]
OK, hab den Fehler gefunden, er kam mit der Gewichtung der Verbrauchswerte nach der Nähe zu heute mit rein.
Hab ihn gefixt in #116 mir 66d2377

**Comment by Manniene** [comment]
> OK, hab den Fehler gefunden, er kam mit der Gewichtung der Verbrauchswerte nach der Nähe zu heute mit rein. Hab ihn gefixt in #116 mir [66d2377](https://github.com/wiggal/GEN24_Ladesteuerung/commit/66d23779a2cd3516bc2ebea54a4667e3db4d8e79)

>> getestet mit  Daysback 4,6,8,20 => alles in Ordnung => Bug behoben
