### ISSUE TITLE
Permission denied in SymoGen24Controller2.py

### ISSUE THREAD

**Issue by neupertd** [wiggal/GEN24_Ladesteuerung#16]
Hallo,

bei mir scheint die Verbindung zum WR nicht zu klappen.
Meine Modbus-Version ist wie in der Anleitung die 0.1.10

Fehlermeldung:
```
symo@zigbee:~/GEN24_Ladesteuerung$ python3 SymoGen24Controller2.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/ping3/__init__.py", line 281, in ping
    sock = socket.socket(socket.AF_INET, socket.SOCK_RAW, socket.IPPROTO_ICMP)
  File "/usr/lib/python3.9/socket.py", line 232, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
PermissionError: [Errno 1] Operation not permitted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/symo/GEN24_Ladesteuerung/SymoGen24Controller2.py", line 207, in <module>
    if ping(config['gen24']['hostNameOrIp']):
  File "/usr/local/lib/python3.9/dist-packages/ping3/__init__.py", line 83, in wrapper
    func_return = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/ping3/__init__.py", line 285, in ping
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_ICMP)
  File "/usr/lib/python3.9/socket.py", line 232, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
PermissionError: [Errno 13] Permission denied

```

Grundsätzlich sollte die Modbus-Verbindung zum WR funktionieren. Vom Timberwolfserver aus klappt das lesen. Dort habe ich jetzt erstmal vorbeugend den Zugriff deaktiviert. WR steht auf Slave und int + SF

Muss der verwendete Linux-User noch in einer bestimmten Gruppe stehen?

**Comment by neupertd** [comment]
Kleiner Nachtrag,

der lesende Zugriff scheint zu funktionieren. Im Log.csv werden aktuelle Werte protokolliert.
z.B.
````
06-12 09:05,3022.9921875,436.5572143554688,9.9,3522.9654541015625,4607,10000,87.1
06-12 09:10,3114.529541015625,439.2223693847656,-1.2,3598.7892456054688,4607,10000,89.6
06-12 09:15,3106.96533203125,511.3999084472656,-7.9,3674.250244140625,4607,10000,92.0
06-12 09:20,-2.544255256652832,548.0938476562501,3137.6,3812.1090698242188,4607,10000,96.9
06-12 09:25,12.231764793395996,533.6843749999998,3279.3,3946.2393798828125,4607,10000,100.0
````

**Comment by wiggal** [comment]
Sieht so aus als ob der ping ein problem hätte.
Welche Version von "ping3" hast du installiert?
Ich habe "ping3             4.0.3"

**Comment by neupertd** [comment]
Hallo,

habe gerade von 4.0.4 auf 4.0.3 ein Downgrade durchgeführt. Die
Fehlermeldung ist aber die gleiche.
Die Vermutung mit ping hatte ich auch schon, kenne mich aber mit Python
nicht aus.


Am Mo., 12. Juni 2023 um 10:59 Uhr schrieb Wiggal ***@***.***

**Comment by wiggal** [comment]
Wie sieht deine config.ini aus, im Bereich 

[gen24]
# IP Wechselrichter
....

**Comment by wiggal** [comment]
Versuch mal das Programm mit sudo auszuführen:
sudo python3 SymoGen24Controller2.py
