### ISSUE TITLE
Problem mit forcast.solar (ohne Solarprognose)

### ISSUE THREAD

**Issue by thorsten-gehrig** [wiggal/GEN24_Ladesteuerung#3]
Erstmal vielen dank für das Script. Super!
Leider habe ich ein kleines Problem.
Solarprognose kann ich leider nicht verwenden (hab 16.5 kWp) - daher verwende ich forecast.solar.
weatherData.json ist angelegt - mit richtigen daten.
Wenn ich den Controller starte bekomme ich aber:

aktuellePrognose:            0
TagesPrognoseGesamt:         0
TagesPrognose - Abzugswerte: 0

Fehler in den Printbefehlen, Ausgabe nicht möglich!
Fehlermeldung: name 'Tagessumme_Faktor' is not defined

Irgendeine Idee was hier schief läuft?
So wie es für mich Ausschaut wird die Berechnung von Tagessumme_Faktor garnicht aufgerufen...
Verbindung wird erfolgreich aufgebaut, WR werte sind auch vorhanden (aktuellePVProduktion, BattStatusProz, ...)
... sieht mir so aus als wenn "print_level=1" (zeile 350) läuft ohne das die wetterdaten berücksichtigt werden - daher "Tagessumme_Faktor" noch nicht gesetzt ist.
Die Wetterdaten werden erfolgreich geladen (zeile 203 - geprüft mit teile 205)
aktuelleVorhersage un dTagesPrognoseGesamt bleiben auf 0 - der Wert von Forcast.Solar wird nicht genutzt

Kann es sein das dein Script nicht mit forcast.solar läuft - und solarprognose "pflicht" ist?

Gruß
Thorsten
PS: Gibt es ein Forum wo du dein Script besprichst - oder ist hier der richtige Platz?

**Comment by wiggal** [comment]
Der Ort ist schon richtig hier, kannst mich aber auch auf www.photovoltaikforum.com in der Konversation erreichen, dort bin ich öfters.
Kannst du mir bitte die gesamte Ausgabe und die weatherData.json zukommen lassen, dann sehe ich mir das Problem mal an.

**Comment by wiggal** [comment]
Habe den Fehler gefunden.
Wenn die Ladung der Batterie in %  unter "MindBattLad" ist, läuft das Programm nicht in die Ermittlung der Ladewerte mit den Prognosewerten sondern lädt die Batterie mit "MaxLadung", was so korrekt ist.
Dadurch war die Variable "Tagessumme_Faktor" nicht belegt (Fehler im Programm).
Werde ich mit der 0.7.6 abfangen.

**Comment by wiggal** [comment]
test

**Comment by wiggal** [comment]
OK
hab die neue Version 0.7.6 rausgehauen.
Könntest sie du bitte bezüglich deines Problems testen.

**Comment by wiggal** [comment]
Fehler beseitigt
