### ISSUE TITLE
Meldung  "dataAgeMaxInMinutes" noch nicht abgelaufen

### ISSUE THREAD

**Issue by modezz** [wiggal/GEN24_Ladesteuerung#34]
Die Minuten aus "dataAgeMaxInMinutes" 30 Minuten sind noch nicht abgelaufen!!
[Now: 2023-11-04 16:55:59.995706] [Data created: 2023-11-04 15:56:00] -> age in min: 59.99992843333334

entweder verstehe ich es nicht oder er schreib es immer raus unabhängig ob true oder false:

 **if (dateCreated):
            diff = now - dateCreated
            dataAgeInMinutes = diff.total_seconds() / 60**
            # print(f'[Now: {now}] [Data created:  {dateCreated}] -> age in min: {dataAgeInMinutes}')
            **print('Die Minuten aus "dataAgeMaxInMinutes" ', dataAgeMaxInMinutes ,' Minuten sind noch nicht abgelaufen!!')
            print(f'[Now: {now}] [Data created:  {dateCreated}] -> age in min: {dataAgeInMinutes}')
            if (dataAgeInMinutes < dataAgeMaxInMinutes):                
                dataIsExpired = False**

weather.json ist allerdings aktuell  - ev könnte man es im gui anzeigen von wann die letzte prognose ist damit man sieht ob der cronjob funktioniert

**Comment by wiggal** [comment]
OK,
die Meldung war an der faschen Stelle im Skript, danke für den Hinweis.
Fehler gefixt.
Vll. kannst du es testen.

Nochmal Danke
Wiggal

**Comment by wiggal** [comment]
> ..... - ev könnte man es im gui anzeigen von wann die letzte prognose ist damit man sieht ob der cronjob funktioniert

gute Idee werd ich mal einbauen 👍

**Comment by wiggal** [comment]
Erledigt mit Version 0.11.0
