### ISSUE TITLE
Python Fehler

### ISSUE THREAD

**Issue by fhemwj** [wiggal/GEN24_Ladesteuerung#5]
Hallo,
ich kann die Scripte leider nicht starten. z.B. Logging:
/opt/GEN24_Ladesteuerung# ./start_LoggingSymoGen24.sh
Traceback (most recent call last):
  File "LoggingSymoGen24.py", line 95, in <module>
    with open(csv_file, 'w', newline='') as student_file:
TypeError: invalid file: PosixPath('Log.csv')

 Auch wenn es die weatherData.json schon gibt kommt folgende Fehlermeldung:

./start_Solarprognose_WeatherData.py.sh
Traceback (most recent call last):
  File "Solarprognose_WeatherData.py", line 70, in <module>
    data = loadWeatherData(weatherfile)
  File "Solarprognose_WeatherData.py", line 24, in loadWeatherData
    with open(weatherfile) as json_file:
TypeError: invalid file: PosixPath('/opt/GEN24_Ladesteuerung/weatherData.json')

Folgendes System läuft:
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian

**Comment by wiggal** [comment]
Welche Pythonversion hast du auf deinem Sysem?

**Comment by fhemwj** [comment]
Python 3.4.2
Wenn ich das so mache wie in dem von dir angeführten Link bekomm ich folgenden Fehler:
Traceback (most recent call last):
  File "LoggingSymoGen24.py", line 95, in <module>
    with open(str(csv_file, 'w', newline='')) as student_file:
TypeError: 'newline' is an invalid keyword argument for this function

**Comment by wiggal** [comment]
Klammer zu nach csv_file

**Comment by fhemwj** [comment]
danke - diesen Fehler behoben ☺
nun noch: wenn ich den Script aus dem Verzeichnis aufrufe läuft er sauber durch,
lass ich den Cronjob laufen kommt:
"config file not found."
- hast du dafür auch ne Lösung?

**Comment by wiggal** [comment]
wie sieht dein Crontabeintrag aus?
Wo liegen die Dateien?

**Comment by fhemwj** [comment]
0,5,10,15,20,25,30,35,40,45,50,55 5-20 * * * root /opt/GEN24_Ladesteuerung/start_LoggingSymoGen24.sh
die Dateien liegen unter /opt/GEN24_Ladesteuerung/

**Comment by wiggal** [comment]
Was macht das  "root" vor dem Befehl?
Das kenn ich so nicht?

**Comment by fhemwj** [comment]
das mit dem kompletten Pfad hatte ich auch schon getestet.
das root kommt vom Webmin,  die crontab sieht so aus:
*/5 05-20 * * * /opt/GEN24_Ladesteuerung/start_LoggingSymoGen24.sh
*/5 04-20 * * * /opt/GEN24_Ladesteuerung/start_SymoGen24Controller2.sh
33 6,8,10,12,14,16 * * * /opt/GEN24_Ladesteuerung/start_WeatherDataProvider2.sh
8 5,8,11,14 * * * /opt/GEN24_Ladesteuerung/start_Solarprognose_WeatherData.py.sh

**Comment by wiggal** [comment]
Ich kann den Fehler nicht nachvollziehen, bei mir klappt`s mit den Cronjobs.
Führ den Befehl aus dem Cronjob mal genau so auf der shell aus:
/usr/bin/python3 SymoGen24Controller2.py

**Comment by wiggal** [comment]
Und wie siehts aus, hast du den Fehler beheben können?

**Comment by wiggal** [comment]
Wegen fehlender Rückmeldung geschlossen!!
