### ISSUE TITLE
Ladewert um 0:01 rücksetzen?

### ISSUE THREAD

**Issue by modezz** [wiggal/GEN24_Ladesteuerung#65]
Servus Wiggal,

wenn z.B. von Solarprognose abgerufen wird und daten erst ab 07:00 bereit stehen aber ab 06:00 schon Leistung am Dach ist dann wird mit dem letzten Wert geladen evtl kann man den um 00:01 auf 0 setzten?

************* BEGINN: 2024-05-20 06:56:02.452714 *************

######### L A D E S T E U E R U N G #########

aktuellePrognose: 0
RestTagesPrognose: 14564
PrognoseAbzugswert/Stunde: 2079
Grundlast_Summe für Tag: 1820
aktuellePVProduktion/Watt: 368
aktuelleEinspeisung/Watt: 8
aktuelleBatteriePower/Watt: -123
GesamtverbrauchHaus/Watt: 237
aktuelleBattKapazität/Watt: 1946
Batteriestatus in Prozent: 82.4 %
LadewertGrund: Prognose ist 0 Watt, deshalb nicht schreiben!
Bisheriger Ladewert/Watt: 4999
Bisheriger Ladewert/Prozent: 48.82 %
Neuer Ladewert/Watt: 0
Neuer Ladewert/Prozent: 0.0 %
newPercent_schreiben: 0

Alte und Neue Werte unterscheiden sich weniger als die Schreibgrenzen des WR, NICHTS zu schreiben!!

Daten wurden in die SQLite-Datei gespeichert!
************* ENDE: 2024-05-20 06:56:02.577673 *************

************* BEGINN: 2024-05-20 07:01:03.143044 *************

######### L A D E S T E U E R U N G #########

aktuellePrognose: 2
RestTagesPrognose: 14564
PrognoseAbzugswert/Stunde: 2110
Grundlast_Summe für Tag: 1795
aktuellePVProduktion/Watt: 445
aktuelleEinspeisung/Watt: 11
aktuelleBatteriePower/Watt: -186
GesamtverbrauchHaus/Watt: 248
aktuelleBattKapazität/Watt: 1935
Batteriestatus in Prozent: 82.5 %
LadewertGrund: Prognoseberechnung / BatSparFaktor
Bisheriger Ladewert/Watt: 4999
Bisheriger Ladewert/Prozent: 48.82 %
Neuer Ladewert/Watt: 0
Neuer Ladewert/Prozent: 0.0 %
newPercent_schreiben: 1 

Danke!
Gruß

**Comment by wiggal** [comment]
Hi @modezz,

ich sehe was du meinst, dieses Problem hatte ich bisher noch nicht, vermutlich weil ich bereits um 5:00 die Erste Prognose anfordere und meine Prognoseberechnung anscheinend besser passt.
Eine Prognose müsste trotz Anforderung erst um 7:00 vorhanden sein, da ja immer zwei Tage in der "weatherData.json" drin sind.

Trotzdem könnte ich das Problem lösen, indem ich die Schreibsperre aus dem Grund
`Prognose ist 0 Watt, deshalb nicht schreiben!`
auf folgenden ändere,
`PVProduktion < 10 Watt, deshalb nicht schreiben!`

Was meist du dazu, oder hab ich hier eine Denkfehler?
Wiggal

**Comment by modezz** [comment]
> Unter Benutzereinstellungen sollte Verwende die Benutzerzeitzone in der API nicht an gehackt sein (glaube ich),
dann sollten die Werte in der Webansicht mit denen in der weatherData.json übereinstimmen und plausibel sein.<

Yep das wars - nun geht die Prognose ab 05:00 los

ist bei meiner 10kw Anlage kein Thema aber bei einer 40KW Anlage die produziert auch in den Morgenstunden schon ganz ordentlich und lädt natürlich den Speicher ....

DANKE!

**Comment by wiggal** [comment]
ok, seh ich auch so, ich bau die Prüfung von Prognose auf Produktion um 😉

**Comment by wiggal** [comment]
Erledigt durch Commit
