### ISSUE TITLE
WeatherDataProvider2.py holt eine Daten mehr bzw speichte keine daten mehr

### ISSUE THREAD

**Issue by modezz** [wiggal/GEN24_Ladesteuerung#70]

**Comment by wiggal** [comment]
hi, kommt da noch was, oder kann ich den schließen

**Comment by modezz** [comment]
entweder hat sich an den Daten was geändert  zuminstet bekomme ich nachdem ich :
`except Exception as error:
        # handle the exception
        print("An exception occurred:", type(error).__name__)
`
reigebastelt habe nun folgenden fehler:

`An exception occurred: AttributeError
`

**Comment by modezz** [comment]
ok nach all den versuchen bin ich aktuell im rate limit - gebe wieder bescheid...

**Comment by modezz** [comment]
OK
Daten kommen: {'result': {'watts': {'2024-06-16 05:05:30': 0, '2024-06-16 05:15:00': 23, '2024-06-16 06:00:00': 74, '2024-06-16 07:00:00': 154, '2024-06-16 08:00:00': 250, '2024-06-16 09:00:00': 390, '2024-06-16 10:00:00': 604, '2024-06-16 11:00:00': 819, '2024-06-16 12:00:00': 995, '2024-06-16 13:00:00': 1223, '2024-06-16 14:00:00': 1618, '2024-06-16 15:00:00': 1961, '2024-06-16 16:00:00': 1996, '2024-06-16 17:00:00': 1774, '2024-06-16 18:00:00': 1443, '2024-06-16 19:00:00': 955, '2024-06-16 20:00:00': 543, '2024-06-16 21:08:54': 0, '2024-06-17 05:05:33': 0, '2024-06-17 05:15:00': 36, '2024-06-17 06:00:00': 107, '2024-06-17 07:00:00': 200, '2024-06-17 08:00:00': 281, '2024-06-17 09:00:00': 416, '2024-06-17 10:00:00': 713, '2024-06-17 11:00:00': 1112, '2024-06-17 12:00:00': 1469, '2024-06-17 13:00:00': 1590, '2024-06-17 14:00:00': 1421, '2024-06-17 15:00:00': 1237, '2024-06-17 16:00:00': 1130, '2024-06-17 17:00:00': 995, '2024-06-17 18:00:00': 818, '2024-06-17 19:00:00': 604, '2024-06-17 20:00:00': 370, '2024-06-17 21:09:17': 0}, 'watt_hours_period': {'2024-06-16 05:05:30': 0, '2024-06-16 05:15:00': 2, '2024-06-16 06:00:00': 36, '2024-06-16 07:00:00': 114, '2024-06-16 08:00:00': 202, '2024-06-16 09:00:00': 320, '2024-06-16 10:00:00': 497, '2024-06-16 11:00:00': 712, '2024-06-16 12:00:00': 907, '2024-06-16 13:00:00': 1109, '2024-06-16 14:00:00': 1421, '......etc

endet aber mit Keyerror

**Comment by modezz** [comment]
File "/home/GEN24/WeatherDataProvider2.py", line 81, in <module>
    data = loadLatestWeatherData(config)
  File "/home/GEN24/WeatherDataProvider2.py", line 37, in loadLatestWeatherData
    dict_watts[key]=dict_watts[key]+value
KeyError: '2024-06-16 21:00:00'

**Comment by modezz** [comment]
yep mit nur einer fläche funktioniert das wieder - die addidion 2er flächen per key timespamp scheint aktuell nicht zu matchen

**Comment by wiggal** [comment]
Hi, das ging doch schon, oder?
kannst du bitte mal die config.ini im Bereich [forecast.solar] und [forecast.solar2] posten.

**Comment by wiggal** [comment]
Oder hier meine Vermutung:
die Koordinaten im Bereich [forecast.solar] und [forecast.solar2] müssen identisch sein, sonnst hast du unterschiedliche Sonnenauf- und untergänge.

**Comment by wiggal** [comment]
Hi, habe es mal umgebaut:
es werden nur noch die Koordinaten von [forecast.solar] verwendet, in  [forecast.solar2] kann man die Zeilen entfernen.
Da man auch bei forecast.solar nicht unendlich viele Anforderungen machen kann (hab ich nicht gewusst) hab ich den Fehler abgefangen.

**Comment by modezz** [comment]
> Oder hier meine Vermutung:
> die Koordinaten im Bereich [forecast.solar] und [forecast.solar2] müssen identisch sein, sonnst hast du unterschiedliche  Sonnenauf- und untergänge.

war auch mein erster Gedanke aber alles bis zur nachkommastelle gleich

**Comment by wiggal** [comment]
welche Ausrichtungen hast du?

**Comment by modezz** [comment]
O/W - hat aber wie gesagt schon alles tadellos funktioniert.....

**Comment by wiggal** [comment]
> File "/home/GEN24/WeatherDataProvider2.py", line 81, in data = loadLatestWeatherData(config) File "/home/GEN24/WeatherDataProvider2.py", line 37, in loadLatestWeatherData dict_watts[key]=dict_watts[key]+value KeyError: '2024-06-16 21:00:00'
> 
> sind 2 dachflächen - die 2 kommt mit 21:00:00 daher die 1. mit 21:08:54
> 
OK, dann muss ich halt abfragen,  ob der Key existiert 😁

**Comment by modezz** [comment]
> OK, dann muss ich halt abfragen, ob der Key existiert 😁

und ich würd dann natürlich gerne testen...... 👍

**Comment by wiggal** [comment]
OK, habs hochgeladen.
Bei unterschiedlichen key bei Sonnenauf- bzw untergang wird nur der Wert aus Abfrage eins verwendet, da er eh recht klein ist, dürfte es keine große auswirkung haben.
Wenn dein Test klapp, bau ichs in die nächste Version, vermutlich morgen ein.
Schönen Gruß

**Comment by modezz** [comment]
perfekt - funtioniert problemlos! - Danke!
SG
