### ISSUE TITLE
forecast.solar - aktuell probleme?

### ISSUE THREAD

**Issue by modezz** [wiggal/GEN24_Ladesteuerung#74]
fyi - seit gestern abend

bekomme als response per Browser : Something went wrong, please try later

und im script nach modifikation:

Invalid JSON syntax: **Expecting value: line 1 column 1 (char 0)**

mal abwarten..

Gruß

**Comment by wiggal** [comment]
> bekomme als response per Browser : Something went wrong, please try later

Wenn du was aufrufst?

**Comment by modezz** [comment]
beim aufruf von **https://api.forecast.solar/estimate/xx.xx/xx.xx/32/-90/5 im Browser**
mit scipt **/home/GEN24/WeatherDataProvider2.py**


aber aktuellkommt folendes:

> Unfortunately, the API is temporarily out of service due to maintenance work. However, we will be back online shortly.

**Comment by wiggal** [comment]
OK,
ich hab Folgendes im LOG:

Traceback (most recent call last):
  File "/home/GEN24/Solcast_WeatherData.py", line 160, in <module>
    data = loadLatestWeatherData()
  File "/home/GEN24/Solcast_WeatherData.py", line 36, in loadLatestWeatherData
    json_data1 = dict(json.loads(apiResponse.text))
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Werde es bei Gelegenheit abfangen, bitte issue nicht schließen.

**Comment by modezz** [comment]
scheint wieder OK zu sein -
