### ISSUE TITLE
Fehler in neuer Eigenverbrauchssteuerung

### ISSUE THREAD

**Issue by zellneralex** [wiggal/GEN24_Ladesteuerung#77]
https://github.com/wiggal/GEN24_Ladesteuerung/blob/608085623c3cf28004181fd1849434bc09f93aa6/http_SymoGen24Controller2.py#L476

gehört alles 2 eingerückt da du sonst 

Traceback (most recent call last):
File "/home/pi/GEN24/http_SymoGen24Controller2.py", line 476, in
if Dauer_Nacht_Std > 1:
NameError: name 'Dauer_Nacht_Std' is not defined

erzeugst, der Rest darin natürlich auch.

Gruß Alex

**Comment by wiggal** [comment]
Danke dir für die Meldung,
wenn EigenverbOpt_steuern ausgeschaltet ist, hatte ich nicht getestet.
Habs bereinigt, vll. kannst du es nochmal testen.

**Comment by zellneralex** [comment]
Damit geht es wieder, ich krieg seit kurzen auch nen Solcast Fehler den muss ich mir aber erst ansehen. Den hab ich auch erst heute entdeckt als ich im log nachgesehen hab.
