### ISSUE TITLE
Ladesteuerung "hängt" in einer "nicht-schreiben-loop"

### ISSUE THREAD

**Issue by jaydee73** [wiggal/GEN24_Ladesteuerung#79]
Hi Wiggal,

ich habe heute (erstmalig) ein seltsames Phänomen beobachtet. Habe gestern auf 0.21.2 upgedated und dabei auch erstmalig die Akkuschonung auf 1 gesetzt, wobei ich mir nicht sicher bin, ob das damit überhaupt zu tun hat.

Folgendes Verhalten:
Gestern Abend ging das Tool über die Akkuschonung auf 0,2C und 0,1C. So weit, so normal.

Heute um 0 Uhr gab es dann folgenden Aufruf:

`******* BEGINN: 2024-07-05 00:00:01.182925 *******

## MODBUS LADESTEUERUNG ###
aktuellePrognose: 0
RestTagesPrognose: 28704
PrognoseAbzugswert/Stunde: 1393
Grundlast_Summe für Tag: 8500
aktuellePVProduktion/Watt: 1
aktuelleEinspeisung/Watt: 183
aktuelleBatteriePower/Watt: 248
GesamtverbrauchHaus/Watt: 66
aktuelleBattKapazität/Watt: 1282
Batteriestatus in Prozent: 83.3 %
LadewertGrund: Nicht schreiben, da PVProduktion < 10 Watt!
Bisheriger Ladewert/Watt: 768
Bisheriger Ladewert/Prozent: 10.0 %
Neuer Ladewert/Watt: 0
Neuer Ladewert/Prozent: 0.0 %
newPercent_schreiben: 0

Alte und Neue Werte unterscheiden sich weniger als die Schreibgrenzen des WR, NICHTS zu schreiben!!

Fallback ist eingeschaltet.
Fallback 18270 geschrieben.
InOutWRte_RvrtTms_Fallback: 18270
StorageControlMode: 3

************* ENDE: 2024-07-05 00:00:01.302104 ************* `

Es wurde also nichts geschrieben, da Schreibgrenze. War in der Nacht auch ok, da sowieso null. 

Aus diesem "Modus" kommt der WR aber nun nicht mehr raus. Heute früh, nachdem die PV wieder Ertrag bringt, ist der Ladewert weiterhin 10%, obwohl eigentlich "Prognoseberechnung/Battspar" greifen würde, sprich er eigentlich null in die Batterie bringen müsste. Er bringt aber weiterhin die 10% rein:

`******* BEGINN: 2024-07-05 07:20:01.428179 *******

## MODBUS LADESTEUERUNG ###
aktuellePrognose: 22
RestTagesPrognose: 26892
PrognoseAbzugswert/Stunde: 2627
Grundlast_Summe für Tag: 4833
aktuellePVProduktion/Watt: 1270
aktuelleEinspeisung/Watt: 327
aktuelleBatteriePower/Watt: -738
GesamtverbrauchHaus/Watt: 205
aktuelleBattKapazität/Watt: 1497
Batteriestatus in Prozent: 80.5 %
LadewertGrund: Prognoseberechnung / BatSparFaktor
Bisheriger Ladewert/Watt: 768
Bisheriger Ladewert/Prozent: 10.0 %
Neuer Ladewert/Watt: 0
Neuer Ladewert/Prozent: 0.0 %
newPercent_schreiben: 0

Alte und Neue Werte unterscheiden sich weniger als die Schreibgrenzen des WR, NICHTS zu schreiben!!

Fallback ist eingeschaltet.
InOutWRte_RvrtTms_Fallback: 18270
StorageControlMode: 3

************* ENDE: 2024-07-05 07:20:01.434809 *************
`

Vermutlich geschieht dies, weil er aufgrund der SchreibgrenzeUnten nie die 0 geschrieben hat, da die Differenz zwischen 768 und 0 dafür nicht gereicht hat. Ich hätte allerdings gedacht, dass er nachts sowieso einmal quasi einen "Reset" macht, sprich die Null einmal schreibt, unabhängig von Schreibgrenzen etc.

Hast du dazu eine Meinung? Irgendwie erscheint mir das Verhalten zwar programmiertechnisch logisch, aber ist es auch sinnvoll so?

Gruß,
JD

Zusätzliche Anmerkung: Mittlerweile ist der Akku wieder bei 83%, er schreibt aber trotzdem noch Prognoseberechnung:
Batteriestatus in Prozent: 82.7 %
LadewertGrund: Prognoseberechnung / BatSparFaktor 
=> Sollte hier nicht eigentlich ab 80% auch wieder "Akkuschonung 0,2C" stehen?

**Comment by wiggal** [comment]
> Zusätzliche Anmerkung: Mittlerweile ist der Akku wieder bei 83%, er schreibt aber trotzdem noch Prognoseberechnung: Batteriestatus in Prozent: 82.7 % LadewertGrund: Prognoseberechnung / BatSparFaktor => Sollte hier nicht eigentlich ab 80% auch wieder "Akkuschonung 0,2C" stehen?

Das ist normal, da der Batteriesparmodus nur greift, wenn die Ladeleistung über 0,2C bzw. 0,1C liegt.

Das andere Problem muss ich erst analysieren, dazu brauch ich noch folgende INFO.
Eigentlich hätte die Ladeleistung nach BattVollUm und wenn die Batterieschonung nicht greift auf MaxLadung schalten sollen.

Könntest du mit bitte das Logfile (mindestens gestern und heute) gezippt hier anhängen.

**Comment by jaydee73** [comment]
Anbei das Log. Läuft seit vorgestern (habe ich neu gemacht nach dem Update).
[Crontab.log.zip](https://github.com/user-attachments/files/16108650/Crontab.log.zip)

**Comment by wiggal** [comment]
Ok, hab das Problem gefunden:
Das Problem bei dir ist, dass die Prognosen sehr stark von der tatsächlichen Produktion abweicht, z.B.:
```
BEGINN:  2024-07-04 21:40:01.088945
aktuellePrognose:            2860
aktuellePVProduktion/Watt:   27
LadewertGrund:  Akkuschonung: Ladestand > 90%, Ladewert = 0.1C
```
spätestens hier müsste die Akkuschonung abschalten und durch `LadewertGrund:  Stunde aus BattVollUm erreicht!! ` auf MaxLadung geschaltet werden.
Dies ist nämlich an die Bedingung `aktuellePrognose - Grunlast/2 > Ladewert 1.0C` gekoppelt.

Die Prognose sollte zumindest annähernd an mit der Produktion übereinstimmen, sonst funktionieren auch die Prognoseberechnungen nicht richtig. Schau mal, ob du da noch etwas optimieren kannst.

Ich werde bei Gelegenheit mal schauen, ob ich das Problem im Skript irgendwie abfangen kann.

**Comment by jaydee73** [comment]
Ok, Danke für die Analyse. Selbst optimieren wird aber vermutlich schwierig sein. Ich nutze solarprognose mit mosmix und hatte ja selbst mal zwei Wochen lang solarprognose und solcast parallel laufen lassen und mit den Real-Werten verglichen (https://github.com/wiggal/GEN24_Ladesteuerung/discussions/59#discussioncomment-9172845). Fazit war, dass beide auch mal nen Ausreißer haben, der nicht zur Realität passt. Und das war auf den gesamten Tag gesehen. Wenn ich dich richtig verstanden habe, kann hier aktuell ein einziger nicht passender Prognosewert das Verhalten hervorrufen. Das kann ja grundsätzlich immer mal vorkommen, dass einzelne Prognosewerte nicht zur Realität passen, oder nicht?

**Comment by wiggal** [comment]
Ein einzelner Ausreißer verfälscht die Prognosewerte nur ein bisschen, da immer ein Mittelwert aus drei Prognosewerten gebildet wird (eine Stunde vor und zurück und die Aktuell und das fließend). 
Es scheint aber bei dir eher eine zeitliche Verschiebung zu sein (ich schätze mal zwei Stunden), da die Prognose morgens zu spät steigt und abends zu lange bleibt.
- Morgens
2024-07-04 09:00:00
aktuellePrognose:            161            # passt eher zu 07:00 aktuellePVProduktion/Watt:   587
aktuellePVProduktion/Watt:   2253
- Abends
2024-07-04 22:00:01
aktuellePrognose:            2589        # passt eher zu 20:00 aktuellePVProduktion/Watt:   1705
aktuellePVProduktion/Watt:   2

Bei solarprognose.de hatten wir ja mal das Problem, dass man unter` Benutzereinstellungen -> Verwende die Benutzerzeitzone` in der API nicht anhacken soll, sonst hat man eine zeitliche Verschiebung.

Die zeitliche Verschiebung müsste man ja im Diagramm schön sehen, wie unter https://github.com/wiggal/GEN24_Ladesteuerung/discussions/71#discussioncomment-9878249

Ansonsten wie gesagt, das Problem, dass er wie bei dir nicht auf dem Maximalwert springt, werde ich abfangen.

**Comment by wiggal** [comment]
OK, hab mal eine neue SymoGen24Controller2.py bzw. http_SymoGen24Controller2.py hochgeladen, ich hoffe, der Fehler ist jetzt weg.

**Comment by jaydee73** [comment]
Super, Danke! Habe ich mir gerade gezogen und in meinen Docker-Container kopiert (ich nutze deine Docker-Version). Ergebnis sehe ich dann ja später am Abend, wenn PV < 10 Watt ist. Melde mich morgen mit dem Ergebnis.

**Comment by jaydee73** [comment]
Nu hat er um 20.35 Uhr auf "Stunde aus BattVollUm erreicht" geswitcht und damit den Maxwert geschrieben:

`******* BEGINN: 2024-07-05 20:30:01.551633 *******

## MODBUS LADESTEUERUNG ###
aktuellePrognose: 1026
RestTagesPrognose: 0
PrognoseAbzugswert/Stunde: 0
Grundlast_Summe für Tag: 0
aktuellePVProduktion/Watt: 357
aktuelleEinspeisung/Watt: 209
aktuelleBatteriePower/Watt: 1
GesamtverbrauchHaus/Watt: 149
aktuelleBattKapazität/Watt: 61
Batteriestatus in Prozent: 99.2 %
LadewertGrund: Akkuschonung: Ladestand > 90%, Ladewert = 0.1C
Bisheriger Ladewert/Watt: 768
Bisheriger Ladewert/Prozent: 10.0 %
Neuer Ladewert/Watt: 768
Neuer Ladewert/Prozent: 10.0 %
newPercent_schreiben: 0

Alte und Neue Werte unterscheiden sich weniger als die Schreibgrenzen des WR, NICHTS zu schreiben!!

Fallback ist eingeschaltet.
InOutWRte_RvrtTms_Fallback: 18270
StorageControlMode: 3

************* ENDE: 2024-07-05 20:30:01.564908 *************

******* BEGINN: 2024-07-05 20:35:01.544358 *******

## MODBUS LADESTEUERUNG ###
aktuellePrognose: 951
RestTagesPrognose: 0
PrognoseAbzugswert/Stunde: 0
Grundlast_Summe für Tag: 0
aktuellePVProduktion/Watt: 422
aktuelleEinspeisung/Watt: 243
aktuelleBatteriePower/Watt: 42
GesamtverbrauchHaus/Watt: 221
aktuelleBattKapazität/Watt: 69
Batteriestatus in Prozent: 99.1 %
LadewertGrund: Stunde aus BattVollUm erreicht!!
Bisheriger Ladewert/Watt: 768
Bisheriger Ladewert/Prozent: 10.0 %
Neuer Ladewert/Watt: 3000
Neuer Ladewert/Prozent: 39.06 %
newPercent_schreiben: 1

Am WR geschrieben: 39.06% = 3000W

Fallback ist eingeschaltet.
InOutWRte_RvrtTms_Fallback: 18270
StorageControlMode: 3

************* ENDE: 2024-07-05 20:35:01.636458 ************* `

Ich glaube, das wolltest du so erreichen, oder war das auch vorher schon so implementiert? Die Code-Änderung bezog sich ja eigentlich nur auf den <10W-Fall. Der ist aktuell (21.25 Uhr) noch nicht erreicht, kommen immer noch 150W vom Dach. ;-)

**Comment by wiggal** [comment]
Ja, das.hätte auch schon früher funktioniert.
Auffällig ist, dass der Unterschied zwischen Prognose und Produktion nicht mehr so groß ist.
Hast du schon mit der neuen Einstellung eine neue Prognose geholt?

**Comment by wiggal** [comment]
Tja, das ging in die Hose.
Nach Mitternacht hat er bei jedem Aufruf die MaxLadung geschrieben.

Man sollte nichts pushen, was nicht getestet ist.
Hab eine neue Version von SymoGen24Controller2.py bzw. http_SymoGen24Controller2.py hochgeladen, die habe ich jetzt auch schon mal getestet.

**Comment by jaydee73** [comment]
Zur den Prognosen-Werten: Ja, die hatten schon die neue Einstellung.

Ja, irgendwie war das noch nicht das gewünschte Ergebnis. Der Vollständigkeit halber hier aber trotzdem noch meine Beobachtungen:

Um 21.45 Uhr war er unter 10W, und hat folgendes gemacht:

`******* BEGINN:  2024-07-05 21:45:01.569588 ******* 

## MODBUS LADESTEUERUNG ###
aktuellePrognose:            144
RestTagesPrognose:           0
PrognoseAbzugswert/Stunde:   0
Grundlast_Summe für Tag:     0
aktuellePVProduktion/Watt:   4
aktuelleEinspeisung/Watt:    211
aktuelleBatteriePower/Watt:  320
GesamtverbrauchHaus/Watt:    113
aktuelleBattKapazität/Watt:  199
Batteriestatus in Prozent:   97.4 %
LadewertGrund:  Nicht schreiben, da PVProduktion < 10 Watt!
Bisheriger Ladewert/Watt:    2999
Bisheriger Ladewert/Prozent: 39.06 %
Neuer Ladewert/Watt:         3000
Neuer Ladewert/Prozent:      39.06 %
newPercent_schreiben:        0

Alte und Neue Werte unterscheiden sich weniger als die Schreibgrenzen des WR, NICHTS zu schreiben!!

Fallback ist eingeschaltet.
InOutWRte_RvrtTms_Fallback: 18270
StorageControlMode:    3

************* ENDE:  2024-07-05 21:45:01.585281 ************* 
`

=> Trotz <10W, hat er also weiterhin maxLadung geschrieben. Das ging bis Mitternacht so weiter. Um 0 Uhr dann folgendes:

`******* BEGINN:  2024-07-06 00:00:00.637795 ******* 

## MODBUS LADESTEUERUNG ###
aktuellePrognose:            0
RestTagesPrognose:           31376
PrognoseAbzugswert/Stunde:   1801
Grundlast_Summe für Tag:     8500
aktuellePVProduktion/Watt:   1
aktuelleEinspeisung/Watt:    187
aktuelleBatteriePower/Watt:  230
GesamtverbrauchHaus/Watt:    44
aktuelleBattKapazität/Watt:  744
Batteriestatus in Prozent:   90.3 %
LadewertGrund:  Prognoseberechnung / BatSparFaktor
Bisheriger Ladewert/Watt:    2999
Bisheriger Ladewert/Prozent: 39.06 %
Neuer Ladewert/Watt:         3000
Neuer Ladewert/Prozent:      0.0 %
newPercent_schreiben:        1

Am WR geschrieben: 0.0% = 3000W

Fallback ist eingeschaltet.
Fallback wurde NICHT geschrieben, da bereits auf den WR geschrieben wurde.
InOutWRte_RvrtTms_Fallback: 18270
StorageControlMode:    3

************* ENDE:  2024-07-06 00:00:00.761792 ************* `

=> Er wechselt also auf 0%, sagt aber, dass 0% = 3000W wären. Das war etwas irritierend. ;-)

Das blieb dann so bis 5.15 Uhr. Da hat er dann auch die Wattzahl auf 0 gesetzt. Geschrieben werden musste aber nichts mehr:

`******* BEGINN:  2024-07-06 05:10:00.782841 ******* 

## MODBUS LADESTEUERUNG ###
aktuellePrognose:            8
RestTagesPrognose:           31376
PrognoseAbzugswert/Stunde:   2489
Grundlast_Summe für Tag:     5916
aktuellePVProduktion/Watt:   60
aktuelleEinspeisung/Watt:    181
aktuelleBatteriePower/Watt:  195
GesamtverbrauchHaus/Watt:    74
aktuelleBattKapazität/Watt:  1920
Batteriestatus in Prozent:   75.0 %
LadewertGrund:  Prognoseberechnung / BatSparFaktor
Bisheriger Ladewert/Watt:    0
Bisheriger Ladewert/Prozent: 0.0 %
Neuer Ladewert/Watt:         0
Neuer Ladewert/Prozent:      0.0 %
newPercent_schreiben:        0

Alte und Neue Werte unterscheiden sich weniger als die Schreibgrenzen des WR, NICHTS zu schreiben!!

Fallback ist eingeschaltet.
InOutWRte_RvrtTms_Fallback: 18270
StorageControlMode:    3

************* ENDE:  2024-07-06 05:10:00.791664 *************`

Mit dieser Einstellung läuft er bis zum aktuellen Zeitpunkt (8.57 Uhr).

Deine "neue" Version spiele ich jetzt gleich mal ein.

**Comment by wiggal** [comment]
>Bisheriger Ladewert/Watt: 2999
> Neuer Ladewert/Watt: 3000

Da haben wir noch ein kleines Rundungsproblem -> FIX

> Er wechselt also auf 0%, sagt aber, dass 0% = 3000W wären. Das war etwas irritierend. ;-)

Da hab ich die Umwandlung in % vergessen, brauche ich in http ja nicht -> FIX

> Das blieb dann so bis 5.15 Uhr. Da hat er dann auch die Wattzahl auf 0 gesetzt. Geschrieben werden musste aber nichts mehr:

Das kann nicht sein, um 21:45 war `Bisheriger Ladewert/Watt: 2999` dann muss er irgendwann vor 5:15 die 0 Watt geschrieben haben.

> Mit dieser Einstellung läuft er bis zum aktuellen Zeitpunkt (8.57 Uhr).

Passt mit der Tagesprognose und dem Akkustand

Da schiebe ich dann nochmal eine Version nach, mit den Fixes zum Rundungsproblem und richtiger Prozentberechnung

**Comment by jaydee73** [comment]
> Das kann nicht sein, um 21:45 war `Bisheriger Ladewert/Watt: 2999` dann muss er irgendwann vor 5:15 die 0 Watt geschrieben haben.

Er hat ja um 0:00 Uhr die 0% geschrieben. Da war jedoch noch 3000 als "NeuerLadewert Watt" angegeben. Diesen Wattwert hat er dann (warum auch immer) um 5.10 auch auf 0 gesetzt. Geschrieben musste das aber nicht mehr werden, weil er ja nur % schreibt, was er eben um 0 Uhr schon gemacht hatte. Also eher ein Anzeigeproblem, denke ich. Oder verstehe ich da was falsch?

**Comment by wiggal** [comment]
OK, jetzt hab ichs gecheckt. Da die Modbbusvariante die Prozente des neuen Ladewertes schreibt, und ich das Umwandeln der 3000W in % vergessen hatte, hat er um 0:00 die 0% geschrieben. Ist in der neuesten Version auch gefixt. 
Beobachten wir mal die heutige Nacht.

**Comment by jaydee73** [comment]
hmmm...kurz nachdem ich die neue Version eingespielt hatte, fing er an, langsam den Ladewert hochzusetzen (ab 11.25 Uhr heute). Mit Erreichen der Schreibgrenze hat er den Wert dann auch erstmalig geschrieben (12.15 Uhr). Hochzählen ging danach aber weiter und hält weiter an.

Die Batterie ist aber schon bei 80% und BattVollUm ist um 18 Uhr. Und die Prognose sagt für heute 43kw, da kommt also auch noch ordentlich was rein. Deswegen verstehe ich nicht ganz, wieso er hier gegen Mittag schon "hochfährt".

Anbei nochmal das Log. Vielleicht hast du dazu ja eine Meinung?
[Crontab.log.zip](https://github.com/user-attachments/files/16115837/Crontab.log.zip)

**Comment by wiggal** [comment]
Hi,
ich würde es grundsätzlich mal nicht groß auffällige erachten.

Wichtig zu wissen ist hierbei, wenn du die Akkuschonung eingeschaltet hast, wird Batterievoll um eine Stunde vorverlegt, da ja am Ende evtl. weniger in den Akku fließt. Ansonsten kommt es auf verschiedene Faktoren an, aber vor allem dem BatSparFaktor.

Du hast nun natürlich, nicht mehr die hohen Prognosen am Abend, was die Berechnung schon auch ein bisschen nach vorne schiebt. Eventuell musst du halt BattVollUm um eine Stunde nach hinten schieben, wenn dir der Akku zu schnell voll wird.

Aber vorerst würde ich mal beobachten.

**Comment by jaydee73** [comment]
Sorry, ich beobachte natürlich heute deutlich intensiver, und dabei ist mir eine weitere Sache aufgefallen:

BattVollUm steht bei mir auf 18 Uhr. Durch die Akkuschonung ja sogar damit quasi 17 Uhr.

In den Logs wird allerdings erst ab 19.50 Uhr der Ladewertgrund "Stunde aus BattVollUm erreicht!!" angezeigt. Hier mal der Eintrag von 19.45 (davor ist es auch so) sowie der um 19.50 Uhr:

`******* BEGINN: 2024-07-06 19:45:01.342909 *******

## MODBUS LADESTEUERUNG ###
aktuellePrognose: 1657
RestTagesPrognose: 0
PrognoseAbzugswert/Stunde: 0
Grundlast_Summe für Tag: 0
aktuellePVProduktion/Watt: 147
aktuelleEinspeisung/Watt: 229
aktuelleBatteriePower/Watt: 303
GesamtverbrauchHaus/Watt: 221
aktuelleBattKapazität/Watt: 744
Batteriestatus in Prozent: 90.3 %
LadewertGrund: Akkuschonung: Ladestand > 90%, Ladewert = 0.1C
Bisheriger Ladewert/Watt: 768
Bisheriger Ladewert/Prozent: 10.0 %
Neuer Ladewert/Watt: 768
Neuer Ladewert/Prozent: 10.0 %
newPercent_schreiben: 0

Alte und Neue Werte unterscheiden sich weniger als die Schreibgrenzen des WR, NICHTS zu schreiben!!

Fallback ist eingeschaltet.
InOutWRte_RvrtTms_Fallback: 18270
StorageControlMode: 3

************* ENDE: 2024-07-06 19:45:01.352026 *************

******* BEGINN: 2024-07-06 19:50:01.298101 *******

## MODBUS LADESTEUERUNG ###
aktuellePrognose: 1622
RestTagesPrognose: 0
PrognoseAbzugswert/Stunde: 0
Grundlast_Summe für Tag: 0
aktuellePVProduktion/Watt: 116
aktuelleEinspeisung/Watt: 215
aktuelleBatteriePower/Watt: 317
GesamtverbrauchHaus/Watt: 218
aktuelleBattKapazität/Watt: 783
Batteriestatus in Prozent: 89.8 %
LadewertGrund: Stunde aus BattVollUm erreicht!!
Bisheriger Ladewert/Watt: 768
Bisheriger Ladewert/Prozent: 10.0 %
Neuer Ladewert/Watt: 3000
Neuer Ladewert/Prozent: 39.06 %
newPercent_schreiben: 1

Am WR geschrieben: 39.06% = 3000W

Fallback ist eingeschaltet.
InOutWRte_RvrtTms_Fallback: 18270
StorageControlMode: 3

************* ENDE: 2024-07-06 19:50:01.385660 ************* `

Ist das auch "erwartetes Verhalten"?

**Comment by wiggal** [comment]
Ja, das Verhalten ist so gewollt, wenn die Akkuschonung eingeschaltet ist.

Wenn BattVollUm erreicht ist, könnte die Batterie ja noch nicht ganz voll und noch viel PV-Leistung da sein, wenn er dann sofort auf MaxLadung schaltet, wäre der Effekt der Batterieschonung ja dahin. Deshalb bleibt die Batterieschonung noch solange erhalten, bis `aktuelleVorhersage - (Grundlast /2) < AkkuschonungLadewert`, und dann kommt erst "Stunde aus BattVollUm erreicht!!" und MaxLadung. Zu dem Zeitpunkt sollte dann auch kaum noch PV-Leistung da sein.

**Comment by jaydee73** [comment]
Moin,

so, ich denke, soweit schaut das nun gut aus. Nach der o. g. erwarteteten Thematik um 19.50 Uhr passierte bis 21.55 Uhr nichts neues. Dann war PV-Ertrag <10W (ohne dass er was geschrieben hat):

`******* BEGINN:  2024-07-06 21:55:01.367333 ******* 

## MODBUS LADESTEUERUNG ###
aktuellePrognose:            56
RestTagesPrognose:           0
PrognoseAbzugswert/Stunde:   0
Grundlast_Summe für Tag:     0
aktuellePVProduktion/Watt:   4
aktuelleEinspeisung/Watt:    253
aktuelleBatteriePower/Watt:  508
GesamtverbrauchHaus/Watt:    259
aktuelleBattKapazität/Watt:  1920
Batteriestatus in Prozent:   75.0 %
LadewertGrund:  Nicht schreiben, da PVProduktion < 10 Watt!
Bisheriger Ladewert/Watt:    2999
Bisheriger Ladewert/Prozent: 39.06 %
Neuer Ladewert/Watt:         3000
Neuer Ladewert/Prozent:      39.06 %
newPercent_schreiben:        0

Alte und Neue Werte unterscheiden sich weniger als die Schreibgrenzen des WR, NICHTS zu schreiben!!

Fallback ist eingeschaltet.
InOutWRte_RvrtTms_Fallback: 18270
StorageControlMode:    3

************* ENDE:  2024-07-06 21:55:01.374009 ************* `

Das lief dann bis Mitternacht, und dann kam:

`******* BEGINN:  2024-07-07 00:00:01.493670 ******* 

## MODBUS LADESTEUERUNG ###
aktuellePrognose:            0
RestTagesPrognose:           41836
PrognoseAbzugswert/Stunde:   1892
Grundlast_Summe für Tag:     8500
aktuellePVProduktion/Watt:   0
aktuelleEinspeisung/Watt:    197
aktuelleBatteriePower/Watt:  221
GesamtverbrauchHaus/Watt:    24
aktuelleBattKapazität/Watt:  2565
Batteriestatus in Prozent:   66.6 %
LadewertGrund:  Nicht schreiben, da PVProduktion < 10 Watt!
Bisheriger Ladewert/Watt:    2999
Bisheriger Ladewert/Prozent: 39.06 %
Neuer Ladewert/Watt:         0
Neuer Ladewert/Prozent:      0.0 %
newPercent_schreiben:        0

Alte und Neue Werte unterscheiden sich weniger als die Schreibgrenzen des WR, NICHTS zu schreiben!!

Fallback ist eingeschaltet.
Fallback 18270 geschrieben.
InOutWRte_RvrtTms_Fallback: 18270
StorageControlMode:    3

************* ENDE:  2024-07-07 00:00:01.593116 ************* `

Neuer Ladewert also auf 0%/0 Watt, aber weiterhin nicht geschrieben.

Geschrieben hat er dann erstmalig um 05.15 Uhr, als sich auch der Ladewert-Grund wieder erstmalig geändert hat (er also erstmalig wieder über 10W war):

`******* BEGINN:  2024-07-07 05:15:00.647767 ******* 

## MODBUS LADESTEUERUNG ###
aktuellePrognose:            20
RestTagesPrognose:           41836
PrognoseAbzugswert/Stunde:   3209
Grundlast_Summe für Tag:     5875
aktuellePVProduktion/Watt:   24
aktuelleEinspeisung/Watt:    174
aktuelleBatteriePower/Watt:  222
GesamtverbrauchHaus/Watt:    72
aktuelleBattKapazität/Watt:  4124
Batteriestatus in Prozent:   46.3 %
LadewertGrund:  Prognoseberechnung / BatSparFaktor
Bisheriger Ladewert/Watt:    2999
Bisheriger Ladewert/Prozent: 39.06 %
Neuer Ladewert/Watt:         0
Neuer Ladewert/Prozent:      0.0 %
newPercent_schreiben:        1

Am WR geschrieben: 0.0% = 0W

Fallback ist eingeschaltet.
InOutWRte_RvrtTms_Fallback: 18270
StorageControlMode:    3

************* ENDE:  2024-07-07 05:15:00.740458 ************* `

Dieser Status ist nun (9.55 Uhr) unverändert.

Für mich schaut das so korrekt aus. Für dich auch?

**Comment by wiggal** [comment]
Ja sieht OK aus.
Bei mir ist die http-version auch ordentlich durchgelaufen. Werd die Änderungen noch die Woche beobachten und dann evtl nächstes Wochenende die neue Version ziehen.
Schönen Tag

**Comment by jaydee73** [comment]
Ich muss doch nochmal nachhaken....irgendwie bin ich der Meinung, das ist heute nicht richtig gelaufen. Der Akku wurde über Nacht nur bis 67% geleert, aber das Script hat direkt wieder mit 3000W reingeladen (=MaxLadung), damit war er dann um 8.55 Uhr schon wieder voll:

<img width="983" alt="Bildschirmfoto 2024-07-12 um 17 49 08" src="https://github.com/user-attachments/assets/38bda69c-21e5-461d-bc28-f389b3579684">

Und am späten Vormittag nochmal. Ein Teil ging raus, und direkt wieder voll geladen.

Wetterprognose für heute 29,6kw. Er hätte also bis abends noch mehr als genug Ertrag gehabt. BattVollUm steht auf 19 Uhr (plus Akkuschonung).

Log nochmal anbei (ist das Log der letzten Tage).

Magst du nochmal schauen, ob du einen Grund für das Verhalten siehst? Ich sehe im Log vermehrt den Eintrag:
`LadewertGrund: Größter Prognosewert 2994 ist kleiner als GrenzwertGroestePrognose 3000 `
Das kannte ich bisher noch nicht. Und verstehe es ehrlich gesagt auch nicht... ;-)
[Crontab.log.zip](https://github.com/user-attachments/files/16196461/Crontab.log.zip)

**Comment by wiggal** [comment]
Hi, ich schaue mir das an, aber ein Bild von der grafischen Aufbereitung wäre nicht schlecht, da man dort die Prognose schön sieht, oder hast du die nicht am Laufen?

**Comment by wiggal** [comment]
Das Problem ist der `GrenzwertGroestePrognose` er steht auf 3000 Watt, das heißt, wenn die kleinste Prognose des Resttages unter dem Wert liegt, wird mit `MaxLadung` geladen. Bei deinen Prognosen musst du den Wert auf etwa 1000 heruntersetzen (ich werde ihn nun mit 1000 ausliefern). Der Wert soll dafür sorgen, dass die Steuerung nicht so stark untersteuert, und der Akku auch bei geringen Prognosen voll wird.

**Comment by jaydee73** [comment]
> Hi, ich schaue mir das an, aber ein Bild von der grafischen Aufbereitung wäre nicht schlecht, da man dort die Prognose schön sieht, oder hast du die nicht am Laufen?

Du meinst PV-Bilanz und QZ-Bilanz? Öhm, doch, die läuft eigentlich mit. Wobei ich sie selten anschaue und gerade feststellen muss, dass auch nix angezeigt wird. Muss ich mal schauen, warum da nichts zu sehen ist. Die SQLite-Datei wurde zuletzt am 17.03. beschrieben...na dann kann ja auch nix angezeigt werden...

**Comment by jaydee73** [comment]
> Das Problem ist der `GrenzwertGroestePrognose` er steht auf 3000 Watt, das heißt, wenn die kleinste Prognose des Resttages unter dem Wert liegt, wird mit `MaxLadung` geladen. Bei deinen Prognosen musst du den Wert auf etwa 1000 heruntersetzen (ich werde ihn nun mit 1000 ausliefern). Der Wert soll dafür sorgen, dass die Steuerung nicht so stark untersteuert, und der Akku auch bei geringen Prognosen voll wird.

Kam der Wert irgendwann mal neu dazu? Mir ist der noch nie aufgefallen... :-( Ja, der steht auf Default (=3000). Habe ich jetzt mal auf 1000 gesetzt.

**Comment by wiggal** [comment]
Version 0.20.1

**Comment by wiggal** [comment]
Die Version 0.21.3 von heute sollte den Fehler beseitigen. Vll. kannst du nochmal schauen, ob der Fehler beseitigt ist.

**Comment by jaydee73** [comment]
ich hatte die geänderte .py ja schon Anfang der Woche aus dem Repo runtergeladen und bei mir im 0.21.2-Container laufen lassen. Hatte alles funktioniert. Aber dann kann ich jetzt ja auch offiziell auf die neue Container-Version upgraden.
