### ISSUE TITLE
Feature Request: DatenQuelle im Webserver und weaterData.json

### ISSUE THREAD

**Issue by zellneralex** [wiggal/GEN24_Ladesteuerung#96]
Wir haben ja 3 Wetter Quellen wovon 2 eigentlich nur als Backup aufgesetzt sind. Ich hatte jetzt das Problem das meine Abweichung immer grösser zu werden schien. Bis ich dann rausgefunden hatte das was nicht stimmte und mein "Erster" Wetter Dienst keine Daten mehr lieferte. 

Darum wäre es gut die String im WebUI um die Quelle zu erweitern:

![image](https://github.com/user-attachments/assets/79eea27c-78bf-4e4b-9d9d-f925934bb143)

Das sollte einfach machbar sein in dem man den json Eintrag "messageCreated" einfach um die Quelle erweitert. Z.B 
`"messageCreated": "2024-08-16 08:33:02; SolCast"`

Ich komme gerade nicht dazu mir das selber anzusehen aber vielleicht ist das ja was für eine neue Version

**Comment by wiggal** [comment]
OK, ist im PR #95 drin

![grafik](https://github.com/user-attachments/assets/26a4ebfb-8299-4e1f-969b-bc07a1619f68)

**Comment by zellneralex** [comment]
Das ging fix, wenn ich zurück bin teste ich.

**Comment by zellneralex** [comment]
Ich kann nix zum Symo Teil vom PR sagen, aber das Einblenden der Datenquelle geht

**Comment by wiggal** [comment]
OK, dann schließe ich den Issues
