### ISSUE TITLE
default_priv.ini wird plötzlich nicht mehr gefunden

### ISSUE THREAD

**Issue by RienSte** [wiggal/GEN24_Ladesteuerung#97]
Hallo @wiggal 

seit heute 09:00 wird plötzlich die default_priv.ini nicht mehr gefunden, siehe log-Eintrag:
ERROR: Konfigdatei CONFIG/default_priv.ini not found.
[Fronius] Connection to Inverter failed on {self.address}. Retrying in 120 seconds
[Fronius] Connection to Inverter failed on {self.address}. Retrying in 120 seconds
[Fronius] Connection to Inverter failed on {self.address}. Retrying in 120 seconds
Traceback (most recent call last):
  File "/home/GEN24_Ladesteuerung/http_SymoGen24Controller2.py", line 32, in <module>
    for element in result_get_time_of_use:
TypeError: 'NoneType' object is not iterable

File liegt aber wie gewohnt an Ort und Stelle, in /home/GEN24_Ladesteuerung/CONFIG/

Was ich um 09:00 gemacht habe bzw. gemacht wurde ist schwer zu sagen... wüsste nicht, dass ich was verändert hätte. Habe auch das git repo neu gepulled (main) ... auch ohne Erfolg.

Woran kann das liegen?

**Comment by wiggal** [comment]
> Hallo @wiggal
> 
> seit heute 09:00 wird plötzlich die default_priv.ini nicht mehr gefunden, siehe log-Eintrag: 
ERROR: Konfigdatei CONFIG/default_priv.ini not found. 
> 
> File liegt aber wie gewohnt an Ort und Stelle, in /home/GEN24_Ladesteuerung/CONFIG/

die CONFIG/default_priv.ini  kann auch fehlerhaft sein, da ist die Meldung nicht ganz zutreffend.
kannst ja mal posten

**Comment by RienSte** [comment]
Das war es.... in Zeile 1 hat sich ein 'b' vor dem [env] versteckt. Danke für den Tipp!

**Comment by RienSte** [comment]
Das war es.... in Zeile 1 hat sich ein 'b' vor dem [env] versteckt. Danke für den Tipp!

**Comment by RienSte** [comment]
Das war es.... in Zeile 1 hat sich ein 'b' vor dem [env] versteckt. Danke für den Tipp!
